### PR TITLE
Fix databroker references and versions

### PR DESCRIPTION
**Pull request by BjoernAtBosch**
* Start renaming Vehicle Data Broker to Kuksa Data Broker (all repo internal references)
* Adapt version refs to dev-container and data broker

### CODE REVIEW

**Review by int0x27 — APPROVED** [review]
looks good, I've already had some of the changes

**Comment by SebastianSchildt** [comment]
Are the failed seat controller tests a problem or to be expected @int0x27  @BjoernAtBosch . If it is unrelated, looks good to merge to me.
Please confirm

**Comment by int0x27** [comment]
> Are the failed seat controller tests a problem or to be expected @int0x27 @BjoernAtBosch . If it is unrelated, looks good to merge to me.

Sure, it is to be expected as token has read only permissions and tries to upload cobertura reports. You can check it on boschglobal it  is passing (although failing due to integration tests that depend on this PR): https://github.com/boschglobal/kuksa.val.services/pull/16

**Review by SebastianSchildt — APPROVED** [review]
lgtm

**Pull request merged**
